"""
Django settings for campus_detection project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))  # 添加这行

AUTH_USER_MODEL = 'webapi.CustomUser'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

SECRET_KEY = os.getenv('SECRET_KEY')  # 从环境变量读取
DEBUG = os.getenv('DEBUG') == 'True'

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# 允许的 Hosts 添加更多选项
ALLOWED_HOSTS = ['smarthit.top', 'localhost', '127.0.0.1','m.smarthit.top']

TIME_ZONE = 'Asia/Shanghai'

USE_TZ = True
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'webapi',
    'llm',
    'corsheaders',
    'rest_framework.authtoken',
    'djoser',
    'channels',
    'django_celery_beat',
    'drf_spectacular',
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('JWT',),
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),        # 访问令牌过期时间：1小时
    'REFRESH_TOKEN_LIFETIME': timedelta(days=3),        # 刷新令牌过期时间：3天
    'ROTATE_REFRESH_TOKENS': True,                     # 刷新访问令牌时也刷新刷新令牌
    'BLACKLIST_AFTER_ROTATION': False,                 # 不在轮换后将旧的刷新令牌列入黑名单
    'UPDATE_LAST_LOGIN': True,                         # 更新最后登录时间
}

DJOSER = {
    'USER_ID_FIELD': 'id',
    'SERIALIZERS': {
        'user': 'webapi.serializers.CustomUserSerializer',
        'user_create': 'webapi.serializers.CustomUserCreateSerializer',
        'current_user': 'webapi.serializers.CustomUserSerializer',
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'authorization',
    'content-type',
    'x-csrftoken',
    'x-requested-with',
]

ROOT_URLCONF = 'campus_detection.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'campus_detection.wsgi.application'

# Channels配置
ASGI_APPLICATION = 'campus_detection.asgi.application'

# Channel层配置 - 使用Redis作为后端
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],  # 使用本地Redis服务器
            # 如果Redis有密码，添加如下配置
            # "hosts": [{'address': ('127.0.0.1', 6379), 'password': 'your-password'}],
        },
    },
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',  # 控制记录日志的最低级别
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'django.log'),  # 设置日志文件路径
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'campus_detection',  # 数据库名
        'USER': os.getenv('DB_USER'),  # 数据库用户名
        'PASSWORD': os.getenv('DB_PASSWORD'),  # 数据库密码
        'HOST': 'localhost',  # 数据库主机地址
        'PORT': '3306',       # 数据库端口号
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Celery 配置
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Celery Beat 配置
CELERY_BEAT_SCHEDULE = {
    'check_terminal_connections': {
        'task': 'webapi.tasks.check_terminal_connections',
        'schedule': 60.0,  # 每分钟执行一次
    },
    'generate_realtime_data_snapshot': {
        'task': 'webapi.tasks.generate_realtime_data_snapshot',
        'schedule': 1800.0,  # 每30分钟执行一次
    },
}


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Pydantic 配置
import pydantic.v1.config
pydantic.v1.config.PYDANTIC_VALIDATOR_REUSE = True

SPECTACULAR_SETTINGS = {
    "TITLE": "慧感云瞻 项目API接口文档",
    "DESCRIPTION": "接口文档",
    "VERSION": "1.0.0",
}

